metricbeat.modules:
  - module: docker
    metricsets:
      [
        "container",
        "cpu",
        "diskio",
        "event",
        "healthcheck",
        "image",
        "info",
        "memory",
        "network",
      ]
    hosts: ["unix:///var/run/docker.sock"]
    period: 10s
    enabled: true

  - module: elasticsearch
    metricsets: ["node", "node_stats", "cluster_stats", "index"]
    period: 10s
    hosts: ["elasticsearch:9200"]
    enabled: true

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true
logging.level: debug
